In [1]:
import numpy as np
from tensorflow.keras.utils import timeseries_dataset_from_array
from sklearn.preprocessing import MinMaxScaler


In [6]:
8214009+(2694*200)

8752809

In [8]:
13472698-8214009

5258689

In [7]:
8752809 - 8214009

538800

In [2]:
DATA_FILE = '../extracted_pdb_trajectory_after_pbc_fix.npy'
Coordinate_array = np.load(DATA_FILE)
Coordinate_array = Coordinate_array.astype(float)
Coordinate_array


array([[ 1.0000e+00,  1.7231e+01,  4.3637e+01, ...,  3.0959e+01,
         4.5453e+01,  1.8329e+01],
       [ 2.0000e+00,  1.6668e+01,  4.3067e+01, ...,  2.9539e+01,
         4.5439e+01,  1.8648e+01],
       [ 3.0000e+00,  1.8274e+01,  4.3245e+01, ...,  2.9978e+01,
         4.2960e+01,  1.8808e+01],
       ...,
       [ 4.9980e+03, -2.7509e+01,  4.1507e+01, ..., -1.4871e+01,
         6.6108e+01, -7.2460e+00],
       [ 4.9990e+03, -2.6269e+01,  4.1051e+01, ..., -1.4907e+01,
         6.6280e+01, -6.4180e+00],
       [ 5.0000e+03, -2.5217e+01,  4.0906e+01, ..., -1.4575e+01,
         6.6412e+01, -6.8250e+00]])

In [3]:
scaler = MinMaxScaler()

Coordinate_array_scalled = scaler.fit_transform(Coordinate_array[:,1:])
Coordinate_array_scalled
# del Forces_array

array([[0.87133268, 0.73456425, 0.83369555, ..., 0.87549571, 0.52083857,
        0.64876646],
       [0.86246179, 0.72493539, 0.82114243, ..., 0.85678713, 0.52051851,
        0.65468373],
       [0.88776668, 0.72794229, 0.7906841 , ..., 0.86257098, 0.46384399,
        0.65765164],
       ...,
       [0.1663883 , 0.6985827 , 0.08938013, ..., 0.27168285, 0.99305   ,
        0.17436468],
       [0.18592632, 0.69087961, 0.06247364, ..., 0.27120855, 0.99698224,
        0.18972361],
       [0.20250213, 0.68843016, 0.06545785, ..., 0.27558267, 1.        ,
        0.18217399]])

In [4]:
Coordinate_array_scalled.shape

(5000, 8076)

In [5]:
import joblib
scaler_file = 'scaler_coo.save'
joblib.dump(scaler,scaler_file)

['scaler_coo.save']

# Split data into training/validation and testing

In [6]:
def get_time_aromic_dataset(data_x,data_y,seq_length,t_func=timeseries_dataset_from_array):
    x = t_func(
        data=data_x,
        targets=None,
        sequence_stride = seq_length,
        sequence_length=seq_length,
        
    )

    y = t_func(
        data=data_y,
        targets=None,
        sequence_stride = seq_length,
        sequence_length=seq_length,
        
    )



    for input in x:
        print(input.shape)
        

    for input in y:
        print(input.shape)


    for batch in zip(x, y):
        inputs, targets = batch

    # targets = np.array(targets).reshape(targets.shape[0],(targets.shape[1]*targets.shape[2]))

    # print('target and features')
    # print(inputs.shape)
    # print(targets.shape)
    return inputs, targets

In [7]:
train_x = Coordinate_array_scalled[:1900,:]
train_y = Coordinate_array_scalled[100:2000,:]

val_x = Coordinate_array_scalled[2000:2900,:]
val_y = Coordinate_array_scalled[2100:3000,:]


test_x = Coordinate_array_scalled[3000:3900,:]
test_y = Coordinate_array_scalled[3100:4000,:]
train_x.shape

(1950, 8076)

In [8]:
x_1 , y_1 = get_time_aromic_dataset(train_x,train_y,100)
vx_1 , vy_1 = get_time_aromic_dataset(val_x,val_y,100)
testx_1 , testy_1 = get_time_aromic_dataset(test_x,test_y,100)
x_1.shape

2023-01-11 13:37:29.083013: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


(39, 50, 8076)
(39, 50, 8076)
(19, 50, 8076)
(19, 50, 8076)
(19, 50, 8076)
(19, 50, 8076)


TensorShape([39, 50, 8076])

In [43]:
actual = scaler.inverse_transform(np.array(testy_1[0,0,:]).reshape(1,8076))
actual.shape

(1, 8076)

In [51]:
actual = scaler.inverse_transform(np.array(testy_1[0,0,:]).reshape(1,8076))
actual.shape



(1, 8076)

In [37]:
actual = Coordinate_array[200,1:].reshape(1,8076)

In [52]:
actual[0]

array([ 6.877, 32.076, 29.468, ..., 72.141, 57.094, 16.561])

In [53]:
arr_lst = actual[0].tolist()
arr_final = []
arr_temp = []
k = 0

for i in arr_lst:
    k +=1
    if k <4:
        arr_temp.append(i)

    if k ==3:
        arr_final.append(arr_temp)
        arr_temp = []
        k =0

In [22]:
from Bio.PDB import PDBParser, PDBIO

io = PDBIO()
p = PDBParser()

In [24]:
structure = p.get_structure("2lhi", "../pdb_example.pdb")


/Users/user/Library/Python/3.9/lib/python/site-packages/Bio/PDB/Atom.py:232: PDBConstructionWarning: Used element 'N' for Atom (name=N) with given element ''
  warnings.warn(msg, PDBConstructionWarning)
/Users/user/Library/Python/3.9/lib/python/site-packages/Bio/PDB/Atom.py:232: PDBConstructionWarning: Used element 'H' for Atom (name=H1) with given element ''
  warnings.warn(msg, PDBConstructionWarning)
/Users/user/Library/Python/3.9/lib/python/site-packages/Bio/PDB/Atom.py:232: PDBConstructionWarning: Used element 'H' for Atom (name=H2) with given element ''
  warnings.warn(msg, PDBConstructionWarning)
/Users/user/Library/Python/3.9/lib/python/site-packages/Bio/PDB/Atom.py:232: PDBConstructionWarning: Used element 'H' for Atom (name=H3) with given element ''
  warnings.warn(msg, PDBConstructionWarning)
/Users/user/Library/Python/3.9/lib/python/site-packages/Bio/PDB/Atom.py:232: PDBConstructionWarning: Used element 'C' for Atom (name=CA) with given element ''
  warnings.warn(msg, PDBCo

In [54]:

i = 0
for model in structure:

    for chain in model:
            for residue in chain: 
                for atom in residue:
                    atom.set_coord(arr_final[i])
                    # anum = atom.get_serial_number() #code added
                    # atom.set_serial_number(anum)    #code added
                    i += 1

In [55]:
io.set_structure(structure)
io.save("out_actual2.pdb", preserve_atom_numbering = True)

In [9]:
def get_atomic_coordinates(arrs):
    for i in list(range(0,arrs.shape[-1],3)):
        print(arrs[:,:,i:(i+3)].shape)

        print(i)
        if i == 0:
            new_arr = arrs[:,:,i:(i+3)]
        else:
            new_arr = np.append(new_arr,arrs[:,:,i:(i+3)],axis=0)
    return new_arr

In [10]:
x_1 = get_atomic_coordinates(x_1)
y_1 = get_atomic_coordinates(y_1)

vx_1  = get_atomic_coordinates(vx_1)
vy_1 = get_atomic_coordinates(vy_1)

# testx_1 = get_atomic_coordinates(testx_1)
# testy_1 = get_atomic_coordinates(testy_1)

(39, 50, 3)
0
(39, 50, 3)
3
(39, 50, 3)
6
(39, 50, 3)
9
(39, 50, 3)
12
(39, 50, 3)
15
(39, 50, 3)
18
(39, 50, 3)
21
(39, 50, 3)
24
(39, 50, 3)
27
(39, 50, 3)
30
(39, 50, 3)
33
(39, 50, 3)
36
(39, 50, 3)
39
(39, 50, 3)
42
(39, 50, 3)
45
(39, 50, 3)
48
(39, 50, 3)
51
(39, 50, 3)
54
(39, 50, 3)
57
(39, 50, 3)
60
(39, 50, 3)
63
(39, 50, 3)
66
(39, 50, 3)
69
(39, 50, 3)
72
(39, 50, 3)
75
(39, 50, 3)
78
(39, 50, 3)
81
(39, 50, 3)
84
(39, 50, 3)
87
(39, 50, 3)
90
(39, 50, 3)
93
(39, 50, 3)
96
(39, 50, 3)
99
(39, 50, 3)
102
(39, 50, 3)
105
(39, 50, 3)
108
(39, 50, 3)
111
(39, 50, 3)
114
(39, 50, 3)
117
(39, 50, 3)
120
(39, 50, 3)
123
(39, 50, 3)
126
(39, 50, 3)
129
(39, 50, 3)
132
(39, 50, 3)
135
(39, 50, 3)
138
(39, 50, 3)
141
(39, 50, 3)
144
(39, 50, 3)
147
(39, 50, 3)
150
(39, 50, 3)
153
(39, 50, 3)
156
(39, 50, 3)
159
(39, 50, 3)
162
(39, 50, 3)
165
(39, 50, 3)
168
(39, 50, 3)
171
(39, 50, 3)
174
(39, 50, 3)
177
(39, 50, 3)
180
(39, 50, 3)
183
(39, 50, 3)
186
(39, 50, 3)
189
(39, 50, 3)
19

In [11]:
np.save('coo1_x_cleaned.npy',x_1)
np.save('coo1_y_cleaned.npy',y_1)
np.save('coo1_vx_cleaned.npy',vx_1)
np.save('coo1_vy_cleaned.npy',vy_1)
np.save('coo1_testx_cleaned.npy',testx_1)
np.save('coo1_testy_cleaned.npy',testy_1)




In [1]:
50*4

200